name: ci
on:
  pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: rustup update stable && rustup default stable
      - run: cargo run -p ci -- pr
