name: Release
permissions:
  contents: write
on:
  push:
    tags:
      - v[0-9]+.*
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/create-gh-release-action@v1
        with:
          # (Optional) Path to changelog.
          changelog: CHANGELOG.md
          # (Optional) Create a draft release.
          # [default value: false]
          draft: false
          # (Required) GitHub token for creating GitHub Releases.
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update rust toolchain
        run: rustup update stable && rustup default stable
      - name: Run dagger [RELEASE]
        run: cargo run -p ci -- release --version="${{github.ref_name}}"
